name: Downloader

on:
  workflow_dispatch:
    inputs:
      LINK:
        description: 'The file link'
        required: true
      FILE:
        description: 'The file name'
        required: true
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up dependencies
      run: sudo apt-get install wget tree
      
    - name: Run
      run: wget -nv '${{ github.event.inputs.LINK }}'
      
    - name: Tree
      run: tree -ash \${{ github.workspace }}

    - name: Rename
      run: mv ./* down
      
    - name: Upload Aritfact (universal)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.FILE }}
        path: ${{ github.workspace }}/down
