name: Payload Dump

on:
  workflow_dispatch:
    inputs:
      LINK:
        description: 'The payload or zip link'
        required: true
      PART:
        description: 'The name of the partition you want to extract'
        required: true
      
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/5ec1cff/payload-dumper
        
    - name: Run
      run: |
        payload_dumper --partitions \${{ github.event.inputs.PART }} \${{ github.event.inputs.LINK }}
        
    - name: Upload Aritfact (universal)
      uses: actions/upload-artifact@v4
      with:
        name: imgs
        path: ${{ github.workspace }}/output/*
